spring:
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

    jackson:
      property-naming-strategy: SNAKE_CASE

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver

#  main:
#    allow-bean-definition-overriding: true

security:
  oauth2:
    jwt:
      signkey: 123@!

server:
  port: 8081
