spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

    jackson:
      property-naming-strategy: SNAKE_CASE

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver

security:
  oauth2:
    jwt:
      signkey: ${SIGN_KEY:MTIzQCE=}
    client:
      clientId: ${CLIENT_ID:testClientId}
      clientSecret: ${CLIENT_SECRET:testSecret}

server:
  port: 8081
