spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

    jackson:
      property-naming-strategy: SNAKE_CASE

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver

aws:
  region: ${AWS_REGION}
  credentials:
    accessKey: ${AWS_ACCESS}
    secretKey: ${AWS_SECRET}

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false

security:
  oauth2:
    jwt:
      signkey: ${SIGN_KEY:123@!}
    client:
      clientId: ${CLIENT_ID:testClientId}
      clientSecret: ${CLIENT_SECRET:testSecret}

server:
  port: 8081
